# Change these first
owner: elara-aerospace # Your GitHub organization or username, where this repository lives
repo: elara-status # The name of this repository

sites:
  - name: Website
    url: https://elara-aerospace.com
    assignees:
      - suriyaa
  - name: GitHub Repositories
    url: https://github.com/elara-aerospace
    assignees:
      - suriyaa
  - name: GitHub DNS (185.199.108.153)
    check: "tcp-ping"
    url: 185.199.108.153
    port: 80
  - name: GitHub DNS (185.199.109.153)
    check: "tcp-ping"
    url: 185.199.109.153
    port: 80
  - name: GitHub DNS (185.199.110.153)
    check: "tcp-ping"
    url: 185.199.110.153
    port: 80
  - name: GitHub DNS (185.199.111.153)
    check: "tcp-ping"
    url: 185.199.111.153
    port: 80
  - name: Hetzner (Windows Virtual Machines)
    check: "tcp-ping"
    url: static.48.70.216.95.clients.your-server.de
    port: 80

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.elara-aerospace.com
  # baseUrl: /elara-status
  logoUrl: https://elara-aerospace.com/assets/images/logo.png
  name: Elara Aerospace Uptime Monitor
  introTitle: "**Uptime Monitor** is the status page for Elara Aerospace IT services."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  favicon: https://elara-aerospace.com/assets/images/favicon/apple-icon-60x60.png

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
